### ISSUE TITLE
What is blah?

### ISSUE THREAD

**Issue by eljojo** [CodePadawans/nano_padawans_test#2]
Hi Girls,
this piece of code is great.

If you want to enable it so other people can work on it (and thus learn even more!) my first recommendation would be naming of variables.

it's said that proper naming is one of the most complex computer science problems, but achieving a decent solution **is possible**.

If you'd like to read about the topic, I could recommend [The Art of Readable Code](http://shop.oreilly.com/product/9780596802301.do)

**Comment by madziaf** [comment]
Hi Jose, 
thanks a lot for your review and all the tips!
Ute got the book, it's a great resource:)
For now, we got read of blah :)

**Comment by nanoparsec** [comment]
We changed the name of the variable.
