### ISSUE TITLE
The Symbol to Proc trick

### ISSUE THREAD

**Issue by eljojo** [CodePadawans/nano_padawans_test#3]
In Ruby,

doing conversions along the line of `strings = symbols.map { |s| s.to_s }` are so common that there's a shortcut for them!

You might want to read about "The Symbol To Proc Trick".
I found this links that explain it fairly well:
- http://www.skorks.com/2013/04/ruby-ampersand-parameter-demystified/ (skip to last paragraph)
- https://stackoverflow.com/questions/1961030/ruby-ampersand-colon-shortcut
- https://stackoverflow.com/questions/1217088/what-does-mapname-mean-in-ruby

**Comment by nanoparsec** [comment]
We updated our code using the Symbol to proc trick
