### ISSUE TITLE
The inherited Callback

### ISSUE THREAD

**Issue by eljojo** [CodePadawans/nano_padawans_test#4]
This one's a bit "for extra points", but if you don't like to write `Test.run_all_tests` (who likes repetitive code amirite?) you could hook into the _Class inherited callback_.

You might read about it in, of course, the official ruby documentation: http://www.ruby-doc.org/core-2.1.2/Class.html#method-i-inherited

**Comment by nanoparsec** [comment]
@eljojo I don't know if I really understand what you mean :)

**Comment by eljojo** [comment]
ping @schultyy ?

**Comment by nanoparsec** [comment]
yeah, ping @schultyy ^^
